# Quem executa este wfw é o alexandrehtrb/FeriadosDoBrasil.
# Devemos bloquear GitHub Actions no repo feriadosdobrasil/feriadosdobrasil.github.io 
# para que ele não execute este wfw.

name: On push to master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # https://cli.github.com/manual/gh_repo_sync
      - name: Sync forked repo
        run: gh repo sync feriadosdobrasil/feriadosdobrasil.github.io --source alexandrehtrb/FeriadosDoBrasil
        env:
          # Devemos usar um token emitido pelo usuário feriadosdobrasil.
          # Esse token deve ter as permissões de Contents (pode fazer merges) 
          # e Workflows (para quando o repo original alterar workflows).
          GH_TOKEN: ${{ secrets.FERIADOSDOBRASIL_GH_TOKEN }}